export const inspectorStyles = {
  root: "misty-transient-scrollbar h-full min-w-0 overflow-auto bg-background px-3 py-3 text-muted-foreground",
  emptyState: "grid h-full min-h-0 content-center justify-items-center gap-3 px-6 text-center text-muted-foreground",
  emptyStateIcon: "grid size-11 place-items-center rounded-full bg-muted text-muted-foreground",
  emptyStateText: "m-0 max-w-52 text-sm leading-relaxed",
  previewCard: "relative isolate grid h-[238px] place-items-center overflow-hidden rounded-lg bg-muted/30 text-muted-foreground",
  previewMedia: "h-full w-full border-0 object-contain",
  audioPreview: "grid h-full w-full content-center justify-items-center gap-3 px-4 text-muted-foreground",
  audioIcon: "grid size-12 place-items-center rounded-full bg-muted text-foreground",
  audioControl: "w-full max-w-[260px]",
  previewOpenButton: "absolute right-2 top-2 z-[3] size-8 opacity-0 shadow-sm transition-opacity focus-visible:opacity-100 group-hover:opacity-100",
  previewLoadingOverlay: "pointer-events-none absolute inset-0 z-[2] bg-muted/70 motion-safe:animate-pulse",
  previewText: "m-0 h-full w-full overflow-auto whitespace-pre-wrap break-words p-3 text-left font-mono text-[11px] leading-[1.45] text-muted-foreground",
  previewStatus: "px-4 text-center text-sm text-muted-foreground",
  folderPreview: "misty-transient-scrollbar h-full w-full overflow-y-auto overflow-x-hidden p-2",
  folderPreviewList: "grid min-w-0 content-start",
  folderPreviewItem: "grid h-auto min-h-9 min-w-0 grid-cols-[28px_minmax(0,1fr)_auto] justify-start gap-2 rounded-md px-2 py-1.5 text-left text-muted-foreground shadow-none hover:bg-accent hover:text-accent-foreground",
  folderPreviewThumb: "grid size-7 place-items-center overflow-hidden",
  folderPreviewName: "min-w-0 overflow-hidden text-ellipsis whitespace-nowrap text-sm font-medium leading-tight",
  folderPreviewSize: "pl-2 text-right text-xs text-muted-foreground",
  archivePreviewSummary: "mb-1.5 flex min-w-0 items-center justify-between gap-2 px-2 text-xs font-medium capitalize text-muted-foreground",
  detailsCard: "mt-3 divide-y divide-border border-t border-border",
  detailRow: "grid gap-1.5 px-3 py-2.5",
  detailLabel: "text-[11px] font-medium capitalize leading-none text-muted-foreground",
  detailValue: "min-w-0 text-sm font-medium leading-snug text-foreground [overflow-wrap:anywhere]",
  editorCard: "mt-2 grid gap-3 border-t border-border px-3 py-3",
  editorLabel: "grid gap-1.5 text-xs font-medium text-muted-foreground",
  editorTextarea: "min-h-[72px] resize-y",
  editorActions: "flex justify-end",
  dots: "inline-flex h-5 items-center gap-1",
  dot: "size-1.5 rounded-full bg-muted-foreground motion-safe:animate-bounce",
} as const;
