import { useEffect, useState } from "react";
import { ArchiveRestore, Ban, CheckCircle2, DatabaseBackup, FolderPlus, HardDrive, RefreshCw } from "lucide-react";
import { ActionButton, Field, StatusLine } from "../../shared/pluginChrome";
import { usePluginJob } from "../../shared/usePluginJob";
import type { PluginPanelProps } from "../types";

type Repository = { id: string; name: string; kind: "local" | "cloud"; location: string; available: boolean; initialized: boolean; lastBackup?: string };
type Snapshot = { id: string; time: string; paths: string[]; hostname?: string; size?: number };

export function BackupsPlugin({ context }: PluginPanelProps) {
  const jobs = usePluginJob(context);
  const [repositories, setRepositories] = useState<Repository[]>([]);
  const [repositoryId, setRepositoryId] = useState("");
  const [snapshots, setSnapshots] = useState<Snapshot[]>([]);
  const [view, setView] = useState<"overview" | "setup" | "snapshots">("overview");
  const [message, setMessage] = useState("Loading backup repositories…");
  const [error, setError] = useState(false);
  const [location, setLocation] = useState("");
  const [sources, setSources] = useState<string[]>(context.selectedPaths);
  const [repositoryKind, setRepositoryKind] = useState<"local" | "cloud">("local");
  const [cloudRemotes, setCloudRemotes] = useState<string[]>([]);
  const loadRepositories = async () => { const result = await context.runHostCommand<{ ok?: boolean; repositories?: Repository[]; cloudRemotes?: string[]; message?: string }>("backups.repositories"); setRepositories(result.repositories ?? []); setCloudRemotes(result.cloudRemotes ?? []); setRepositoryId((id) => id || result.repositories?.[0]?.id || ""); setMessage(result.message ?? (result.repositories?.length ? "Choose a repository and source folders." : "Set up a repository to create your first backup.")); setError(result.ok === false); };
  useEffect(() => { void loadRepositories(); }, [context]);
  const repository = repositories.find((item) => item.id === repositoryId);
  const loadSnapshots = async () => { if (!repositoryId) return; const result = await context.runHostCommand<{ ok?: boolean; snapshots?: Snapshot[]; message?: string }>("backups.snapshots", { repositoryId }); setSnapshots(result.snapshots ?? []); setMessage(result.message ?? `${result.snapshots?.length ?? 0} snapshots found.`); setError(result.ok === false); setView("snapshots"); };
  const chooseFolders = async (multiple: boolean, title: string) => context.runHostCommand<{ paths?: string[] }>("host.pickFolders", { multiple, title });
  const initialize = async () => { const name = (document.querySelector("#backup-name") as HTMLInputElement)?.value; if (!location) { setError(true); setMessage("Choose a local volume folder or enter a connected remote and subpath."); return; } if (!window.confirm(`Initialize an encrypted repository at ${location}?`)) return; const result = await context.runHostCommand<{ ok?: boolean; message?: string }>("backups.repository.init", { kind: repositoryKind, name, location }); setMessage(result.message ?? "Repository initialized."); setError(result.ok === false); if (result.ok !== false) { setView("overview"); await loadRepositories(); } };
  const restore = async (snapshotId: string) => { const picked = await chooseFolders(false, "Choose restore destination"); if (!picked.paths?.[0]) return; if (!window.confirm("Restore this snapshot into a newly created folder? Existing files will not be overwritten.")) return; await jobs.start("backups.restore", { repositoryId, snapshotId, destination: picked.paths[0] }); };
  return <div className="panel-stack backups-panel">
    <header className="panel-title"><h2>Backups</h2><p>Encrypted snapshots to a local volume or a connected Misty cloud remote.</p></header>
    <nav className="subnav" aria-label="Backup sections"><button className={view === "overview" ? "active" : ""} onClick={() => setView("overview")}>Overview</button><button className={view === "snapshots" ? "active" : ""} disabled={!repositoryId} onClick={() => void loadSnapshots()}>Snapshots</button><button className={view === "setup" ? "active" : ""} onClick={() => setView("setup")}>Add repository</button></nav>
    {view === "setup" ? <section className="setup-form"><div className="callout"><HardDrive size={18} /><div><strong>Choose a safe destination</strong><span>Misty rejects the operating-system volume, network mounts, read-only locations, and paths outside the selected volume.</span></div></div><div className="control-grid"><Field label="Repository type"><select id="backup-kind" className="select-input" value={repositoryKind} onChange={(event) => { setRepositoryKind(event.target.value as "local" | "cloud"); setLocation(""); }}><option value="local">Local non-system volume</option><option value="cloud">Connected Misty cloud remote</option></select></Field><Field label="Repository name"><input id="backup-name" className="text-input" placeholder="Studio archive" maxLength={64} /></Field></div><Field label="Destination" hint={repositoryKind === "cloud" ? "Choose a configured remote identity and add a repository subpath." : "Only writable local non-system volumes are accepted."}><div className="input-action"><input className="text-input" list={repositoryKind === "cloud" ? "backup-cloud-remotes" : undefined} value={location} onChange={(event) => setLocation(event.target.value)} placeholder={repositoryKind === "cloud" ? "remote:Misty Backups/device" : "Choose a volume folder"} />{repositoryKind === "local" ? <ActionButton type="button" className="secondary-button" onClick={() => void chooseFolders(false, "Choose a non-system volume").then((result) => setLocation(result.paths?.[0] ?? ""))}>Browse…</ActionButton> : null}</div>{repositoryKind === "cloud" ? <datalist id="backup-cloud-remotes">{cloudRemotes.map((remote) => <option key={remote} value={`${remote}:Misty Backups`} />)}</datalist> : null}</Field><ActionButton type="button" onClick={() => void initialize()}><FolderPlus size={16} />Review and initialize</ActionButton></section> : null}
    {view === "overview" ? <><div className="control-grid"><Field label="Repository"><select className="select-input" value={repositoryId} onChange={(event) => setRepositoryId(event.target.value)}><option value="">No repository configured</option>{repositories.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.available ? item.kind : "unavailable"}</option>)}</select></Field></div>{repository ? <div className="repository-summary"><DatabaseBackup size={20} /><div><strong>{repository.name}</strong><span>{repository.location}</span><small>{repository.available ? repository.lastBackup ? `Last backup ${new Date(Number(repository.lastBackup)).toLocaleString()}` : "Ready for first backup" : "Repository unavailable"}</small></div></div> : null}<div className="source-box"><strong>Source folders</strong><span>{sources.length ? sources.join(", ") : "Choose one or more local folders."}</span></div><div className="action-row"><ActionButton type="button" className="secondary-button" disabled={jobs.running} onClick={() => void chooseFolders(true, "Choose folders to back up").then((result) => result.paths?.length && setSources(result.paths))}><FolderPlus size={16} />Choose sources…</ActionButton><ActionButton type="button" disabled={!repository?.available || !sources.length || jobs.running} onClick={() => void jobs.start("backups.start", { repositoryId, sources })}><DatabaseBackup size={16} />Back up now</ActionButton><ActionButton type="button" className="secondary-button" disabled={!repository?.available || jobs.running} onClick={() => void jobs.start("backups.check", { repositoryId })}><CheckCircle2 size={16} />Verify repository</ActionButton><ActionButton type="button" className="secondary-button" onClick={() => void loadRepositories()}><RefreshCw size={16} />Refresh</ActionButton></div></> : null}
    {view === "snapshots" ? <section className="snapshot-list">{snapshots.length ? snapshots.map((snapshot) => <article key={snapshot.id}><div><strong>{new Date(snapshot.time).toLocaleString()}</strong><span>{snapshot.paths.join(", ")}</span><small>{snapshot.id.slice(0, 12)}{snapshot.size ? ` · ${snapshot.size.toLocaleString()} bytes` : ""}</small></div><ActionButton type="button" className="secondary-button" disabled={jobs.running} onClick={() => void restore(snapshot.id)}><ArchiveRestore size={15} />Restore…</ActionButton></article>) : <div className="empty-state"><ArchiveRestore size={24} /><strong>No snapshots yet</strong><span>Create a backup to establish the first restore point.</span></div>}</section> : null}
    {jobs.running && jobs.job?.progress != null ? <div className="progress-track"><span style={{ width: `${jobs.job.progress}%` }} /></div> : null}
    <StatusLine tone={jobs.job?.status === "failed" || error ? "error" : jobs.job?.status === "completed" ? "success" : "neutral"}>{jobs.job?.error ?? jobs.job?.message ?? message}</StatusLine>
    {jobs.running ? <ActionButton type="button" className="secondary-button cancel-button" onClick={() => void jobs.cancel()}><Ban size={16} />Cancel current operation</ActionButton> : null}
  </div>;
}
