export const routes = {
  root: "/",
  account: "/account",
  accountRegister: "/account/register",
  accountSettings: "/account/settings",
  accountSignIn: "/account/signin",
  agents: "/agents",
  activity: "/activity",
  apps: "/apps",
  // Legacy path, kept so saved bookmarks and misty:// deep links still resolve.
  // LegacyAgentRedirect forwards it to `agents`.
  assistant: "/assistant",
  automations: "/automations",
  browser: "/browser",
  changelog: "/changelog",
  code: "/code",
  diagnostics: "/diagnostics",
  discover: "/discover",
  dock: "/dock",
  files: "/files",
  home: "/home",
  inbox: "/inbox",
  invite: "/invite",
  library: "/library",
  spaces: "/spaces",
  studio: "/studio",
  studioAgents: "/studio/agents",
  studioWorkflows: "/studio/workflows",
  providers: "/providers",
  profile: "/profile",
  register: "/register",
  settings: "/settings",
  signIn: "/signin",
  transfers: "/transfers",
  terminal: "/terminal",
} as const;
