export const routes = {
  root: "/",
  agents: "/agents",
  activity: "/activity",
  browser: "/browser",
  files: "/files",
  invite: "/invite",
  newTab: "/new",
  spaces: "/spaces",
  providers: "/providers",
  scheduled: "/scheduled",
  register: "/register",
  settings: "/settings",
  signIn: "/signin",
} as const;
