mod commands;
mod core;
mod error;
mod runtime;
mod services;

use commands::{
    app_environment_snapshot, app_snapshot, claude_abort, claude_drain_events, claude_send_message,
    claude_status, clipboard_apply_shared, clipboard_native_file_refs,
    clipboard_publish_image_bytes, clipboard_publish_shared, clipboard_set_local,
    clipboard_shared_image_bytes, clipboard_snapshot, clipboard_write_file_refs, devices_snapshot,
    explorer_create_item, explorer_delete_items, explorer_library_record_last_opened,
    explorer_library_record_recent, explorer_library_set_tags, explorer_library_snapshot,
    explorer_list_directory, explorer_open_association, explorer_open_with, explorer_paste_items,
    explorer_path_exists, explorer_path_is_directory, explorer_prepare_drag_items,
    explorer_prepare_open_item, explorer_preview_item, explorer_queue_create_item,
    explorer_queue_delete_items, explorer_queue_paste_blob, explorer_queue_paste_items,
    explorer_queue_paste_text, explorer_queue_rename_item, explorer_queue_rename_items,
    explorer_rename_item, explorer_set_open_association, file_sync_apply, file_sync_compare,
    file_sync_pair_remove, file_sync_pair_save, file_sync_pairs_snapshot, operation_queue_cancel,
    operation_queue_cancel_batch, operation_queue_clear_terminal, operation_queue_redo,
    operation_queue_resolve_conflict, operation_queue_retry, operation_queue_snapshot,
    operation_queue_undo, plugin_command_run, plugin_commands_snapshot, plugin_panel_render,
    providers_config_paths, providers_configure_remote, providers_disconnect_remote,
    providers_refresh, providers_save_remote, providers_select_remote, providers_snapshot,
    providers_test_remote, proxy_snapshot, settings_apply_launch_on_login,
    settings_launch_on_login_snapshot, settings_open_with_associations,
    settings_remove_open_with_association, settings_save, settings_snapshot, shortcuts_save,
    shortcuts_snapshot, transfers_delete_all, transfers_delete_selected, transfers_snapshot,
    workspaces_save, workspaces_snapshot,
};
use runtime::MistyRuntime;
use services::hub::{
    check_system, ensure_local_access_token, ensure_misty_folders, get_clipboard_proxy_snapshot,
    get_misty_process_status, install_misty, install_plugin_bundle, launch_misty,
    open_external_url, probe_paths, read_misty_log, restart_misty, save_authenticated_user,
    save_verified_license, scan_local_plugins, set_plugin_enabled, sign_out_misty, stop_misty,
    uninstall_plugin,
};

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_clipboard_manager::init())
        .plugin(tauri_plugin_deep_link::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_keystore::init())
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_os::init())
        .manage(MistyRuntime::new())
        .invoke_handler(tauri::generate_handler![
            app_snapshot,
            app_environment_snapshot,
            claude_status,
            claude_send_message,
            claude_drain_events,
            claude_abort,
            check_system,
            ensure_misty_folders,
            probe_paths,
            ensure_local_access_token,
            save_authenticated_user,
            save_verified_license,
            sign_out_misty,
            install_misty,
            launch_misty,
            restart_misty,
            stop_misty,
            scan_local_plugins,
            install_plugin_bundle,
            set_plugin_enabled,
            uninstall_plugin,
            get_clipboard_proxy_snapshot,
            get_misty_process_status,
            read_misty_log,
            open_external_url,
            proxy_snapshot,
            clipboard_snapshot,
            clipboard_set_local,
            clipboard_publish_shared,
            clipboard_publish_image_bytes,
            clipboard_apply_shared,
            clipboard_shared_image_bytes,
            clipboard_native_file_refs,
            clipboard_write_file_refs,
            devices_snapshot,
            explorer_list_directory,
            explorer_create_item,
            explorer_rename_item,
            explorer_delete_items,
            explorer_paste_items,
            explorer_prepare_open_item,
            explorer_prepare_drag_items,
            explorer_preview_item,
            explorer_open_with,
            explorer_open_association,
            explorer_set_open_association,
            explorer_path_is_directory,
            explorer_path_exists,
            explorer_library_snapshot,
            explorer_library_record_recent,
            explorer_library_record_last_opened,
            explorer_library_set_tags,
            explorer_queue_create_item,
            explorer_queue_rename_item,
            explorer_queue_rename_items,
            explorer_queue_delete_items,
            explorer_queue_paste_items,
            explorer_queue_paste_text,
            explorer_queue_paste_blob,
            file_sync_pairs_snapshot,
            file_sync_pair_save,
            file_sync_pair_remove,
            file_sync_compare,
            file_sync_apply,
            workspaces_snapshot,
            workspaces_save,
            settings_snapshot,
            settings_save,
            settings_launch_on_login_snapshot,
            settings_apply_launch_on_login,
            settings_open_with_associations,
            settings_remove_open_with_association,
            shortcuts_snapshot,
            shortcuts_save,
            plugin_commands_snapshot,
            plugin_command_run,
            plugin_panel_render,
            providers_snapshot,
            providers_refresh,
            providers_select_remote,
            providers_save_remote,
            providers_test_remote,
            providers_config_paths,
            providers_configure_remote,
            providers_disconnect_remote,
            transfers_snapshot,
            transfers_delete_selected,
            transfers_delete_all,
            operation_queue_snapshot,
            operation_queue_cancel,
            operation_queue_cancel_batch,
            operation_queue_retry,
            operation_queue_undo,
            operation_queue_redo,
            operation_queue_resolve_conflict,
            operation_queue_clear_terminal,
        ])
        .run(tauri::generate_context!())
        .expect("failed to run Misty Tauri app");
}
