// Generated by misty/scripts/sync-file-system-types.mjs from the native IPC contracts.
export interface AppEnvironmentSnapshot {
  homeDir: string;
  mistyDir: string;
  configDir: string;
  dbDir: string;
  cacheDir: string;
  tmpDir: string;
  notesDir: string;
  pluginsPublicDir: string;
  pluginsPrivateDir: string;
  settingsPath: string;
  mistyConfigPath: string;
  workspacesPath: string;
  commandsPath: string;
  serverUrl: string | null;
  serverMode: "hosted" | "self_hosted";
  serverDeploymentId?: string | null;
  serverName?: string | null;
  grpcAddress: string;
  mountPath: string;
  configExists: boolean;
  derivedEnv: Record<string, string>;
}

export interface DeviceSnapshot {
  devices: MountedDevice[];
}

export interface MountedDevice {
  id: string;
  volumeId: string;
  name: string;
  mountPath: string;
  fsType: string;
  isRemovable: boolean;
  isSystem: boolean;
  isExternal: boolean;
  isNetwork: boolean;
  writable: boolean;
  totalBytes: number;
  freeBytes: number;
}

export interface ConnectedDevicesSnapshot {
  enabled: boolean;
  endpointId: string | null;
  addressing: unknown | null;
  relayPolicy: "managed" | "public-development" | "disabled";
  peers: ConnectedPeerStatus[];
  unavailableReason: string | null;
}

export interface ConnectedPeerStatus {
  deviceId: string;
  state: "online" | "authorization_expired" | "connecting" | "offline";
  connectionType: "direct" | "relay" | "unknown";
  authorizationExpiresAt: number;
}

export interface PeerRoot {
  id: string;
  name: string;
  kind: "system" | "volume" | "folder";
  readonly: true;
}

export interface ListDirectoryRequest {
  path?: string | null;
  showHidden?: boolean;
  forceRemoteRefresh?: boolean;
}

export interface DirectoryListing {
  path: string;
  title?: string | null;
  parentPath: string | null;
  location: ExplorerLocation;
  entries: FileEntry[];
  totalCount: number;
  hiddenCount: number;
  modifiedMs?: number | null;
  createdMs?: number | null;
}

export interface ExplorerLocation {
  kind: ExplorerLocationKind;
  providerType: string | null;
  remoteName: string | null;
  remotePath: string | null;
  peerDeviceId?: string | null;
  peerRootId?: string | null;
}

export type ExplorerLocationKind = "local" | "remote_provider" | "remote" | "peer_device";

export interface FileEntry {
  id: string;
  name: string;
  path: string;
  extension: string;
  mimeType: string | null;
  remoteModified: string | null;
  kind: FileKind;
  sizeBytes: number | null;
  modifiedMs: number | null;
  createdMs: number | null;
  readonly: boolean;
  hidden: boolean;
  isDeleted?: boolean;
  location: ExplorerLocation;
}

export type FileKind = "folder" | "file" | "symlink" | "other";

export interface FileMetadataSnapshot {
  path: string;
  kind: string;
  sizeBytes?: number | null;
  readonly: boolean;
  hidden: boolean;
  createdMs?: number | null;
  modifiedMs?: number | null;
  accessedMs?: number | null;
  osTags: string[];
  fields: FileMetadataField[];
  extracted: FileMetadataField[];
}

export interface FileMetadataField {
  label: string;
  value: string;
}

export interface ExplorerPreviewPayload {
  mimeType: string;
  bytes: number[];
}

export interface PasteItemsRequest {
  sources: PasteItem[];
  destinationDirectory: string;
  operation: ClipboardOperation;
  targetName?: string | null;
}

export interface PasteItem {
  path: string;
  isDirectory: boolean;
  sizeBytes?: number | null;
  remoteModified?: string | null;
}

export type ClipboardOperation = "copy" | "move";

export interface CreateItemRequest {
  directory: string;
  name: string;
  kind: CreateItemKind;
}

export type CreateItemKind = "file" | "folder";

export interface RenameItemRequest {
  path: string;
  newName: string;
  sourceIsDirectory?: boolean;
}

export interface DeleteItemsRequest {
  paths: string[];
  permanent?: boolean;
}

export interface OperationQueueSnapshot {
  operations: OperationDescriptor[];
  batches: OperationBatch[];
  conflictDialog: ConflictDialogState;
  activeCount: number;
  maxConcurrent: number;
  redoAvailable: boolean;
  paused: boolean;
  bandwidthLimit: string;
  transferProfileId: string;
  transferProfileName: string;
}

export interface OperationDescriptor {
  operationId: number;
  transferId: number;
  batchId: number;
  parentTransferId: number;
  rootTransferId: number;
  treeDepth: number;
  kind: OperationKind;
  source: OperationEndpoint;
  target: OperationEndpoint;
  conflictPolicy: OperationConflictPolicy;
  status: OperationStatus;
  preserveOrder: boolean;
  retryable: boolean;
  cancelable: boolean;
  undoable: boolean;
  supportsReplace: boolean;
  supportsKeepBoth: boolean;
  title: string;
  errorMessage: string;
  attempt: number;
  paused: boolean;
}

export type OperationKind =
  "copy" | "move" | "create" | "rename" | "delete" | "upload" | "download" | "archive";

export interface OperationEndpoint {
  localPath: string;
  remoteName: string;
  remotePath: string;
}

export type OperationConflictPolicy = "ask" | "replace" | "skip" | "keep_both";

export type OperationStatus =
  | "queued"
  | "in_progress"
  | "waiting_for_resolution"
  | "completed"
  | "failed"
  | "canceled"
  | "skipped";

export interface OperationBatch {
  batchId: number;
  label: string;
  preserveOrder: boolean;
  paused: boolean;
  pausedOperationId: number;
  operationIds: number[];
}

export interface ConflictDialogState {
  open: boolean;
  operationId: number;
  batchId: number;
  applyToBatch: boolean;
  supportsReplace: boolean;
  supportsKeepBoth: boolean;
  selectedPolicy: OperationConflictPolicy;
  title: string;
  sourceLabel: string;
  targetLabel: string;
}

export interface TransferFilter {
  search?: string;
  offset?: number;
  limit?: number;
}

export interface TransferPage {
  rows: TransferRecord[];
  totalCount: number;
  dbPath: string;
}

export interface TransferRecord {
  id: number;
  jobId: number;
  operationId: number;
  batchId: number;
  parentTransferId: number;
  rootTransferId: number;
  treeDepth: number;
  transferType: TransferType;
  itemType: "local" | "remote";
  status: TransferStatus;
  conflictPolicy: string;
  queueTitle: string;
  fileName: string;
  localSourcePath: string;
  localDestPath: string;
  remoteSourceName: string;
  remoteSourcePath: string;
  remoteDestName: string;
  remoteDestPath: string;
  totalBytes: number;
  transferredBytes: number;
  bytesPerSecond: number;
  errorMessage: string;
  detailMessage: string;
  queuedAtMs: number;
  startedAtMs: number;
  completedAtMs: number;
  cancelable: boolean;
  retryable: boolean;
  undoable: boolean;
  undoTokenId: number;
  preserveOrder: boolean;
  paused: boolean;
  attempt: number;
  supportsReplace: boolean;
  supportsKeepBoth: boolean;
}

export type TransferType =
  "upload" | "download" | "create" | "copy" | "move" | "rename" | "delete" | "archive";

export type TransferStatus =
  | "queued"
  | "pending"
  | "in_progress"
  | "waiting_for_resolution"
  | "completed"
  | "failed"
  | "canceled"
  | "skipped"
  | "interrupted";
