import { command } from "./factory";

export const filesShortcutCommands = [
  command("app.toggle_transfers", "Open Transfers", {
    description: "Open the Transfers tool from Files.",
    category: "Files",
    scope: "tool:files",
    mac: "Cmd+Shift+Y",
    windows: "Ctrl+Shift+Y",
    allowInEditable: true,
  }),
  command("app.toggle_plugin_launcher", "Open Extensions", {
    description: "Open installed extensions from Files.",
    category: "Files",
    scope: "tool:files",
    allowShadowing: true,
  }),
  command("clipboard.publish_shared", "Share clipboard", {
    description: "Publish the local clipboard to connected Misty devices.",
    category: "Files",
    scope: "tool:files",
  }),
  command("clipboard.apply_shared", "Use shared clipboard", {
    description: "Apply the latest shared clipboard to this device.",
    category: "Files",
    scope: "tool:files",
  }),
  command("explorer.new_folder", "New folder", {
    description: "Create a folder in the focused Files location.",
    category: "Files",
    scope: "tool:files",
    mac: "Cmd+Shift+N",
    windows: "Ctrl+Shift+N",
    allowInEditable: true,
  }),
  command("explorer.search", "Search Files", {
    description: "Search the focused Files location.",
    category: "Files",
    scope: "tool:files",
    mac: "Cmd+Shift+F",
    windows: "Ctrl+Shift+F",
    allowInEditable: true,
  }),
  command("explorer.rename", "Rename file", {
    description: "Rename the selected file or folder.",
    category: "Files",
    scope: "tool:files",
    mac: "F2",
  }),
  command("explorer.batch_rename", "Batch rename files", {
    description: "Rename multiple selected files together.",
    category: "Files",
    scope: "tool:files",
  }),
  command("explorer.delete", "Move file to Trash", {
    description: "Move the selected file or folder to Trash.",
    category: "Files",
    scope: "tool:files",
    mac: "Delete",
  }),
  command("explorer.download", "Download file", {
    description: "Download the selected remote files or folders.",
    category: "Files",
    scope: "tool:files",
  }),
  command("explorer.open_with", "Open file with application", {
    description: "Choose an application for the selected local file.",
    category: "Files",
    scope: "tool:files",
  }),
  command("explorer.copy", "Copy file", {
    description: "Copy the selected files or folders.",
    category: "Files",
    scope: "tool:files",
    mac: "Cmd+C",
    windows: "Ctrl+C",
  }),
  command("explorer.cut", "Cut file", {
    description: "Cut the selected files or folders.",
    category: "Files",
    scope: "tool:files",
    mac: "Cmd+X",
    windows: "Ctrl+X",
  }),
  command("explorer.paste", "Paste file", {
    description: "Paste files or folders into the current location.",
    category: "Files",
    scope: "tool:files",
    mac: "Cmd+V",
    windows: "Ctrl+V",
  }),
  command("explorer.copy_path", "Copy file path", {
    description: "Copy the selected file or folder path.",
    category: "Files",
    scope: "tool:files",
    mac: "Cmd+Option+C",
    windows: "Ctrl+Alt+C",
  }),
  command("explorer.undo", "Undo Files operation", {
    description: "Undo the last supported Files operation.",
    category: "Files",
    scope: "tool:files",
    mac: "Cmd+Z",
    windows: "Ctrl+Z",
    allowShadowing: true,
  }),
  command("explorer.redo", "Redo Files operation", {
    description: "Redo the last supported Files operation.",
    category: "Files",
    scope: "tool:files",
    mac: "Cmd+Shift+Z",
    windows: "Ctrl+Y",
    allowShadowing: true,
  }),
  command("explorer.refresh", "Refresh Files", {
    description: "Refresh the focused Files location.",
    category: "Files",
    scope: "tool:files",
    mac: "Cmd+R",
    windows: "Ctrl+R",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("explorer.duplicate_finder", "Find duplicate files", {
    description: "Open the duplicate finder for the current Files location.",
    category: "Files",
    scope: "tool:files",
  }),
  command("explorer.compare_with", "Compare files", {
    description: "Compare the selected local file or folder with another item.",
    category: "Files",
    scope: "tool:files",
  }),
  command("explorer.toggle_hidden", "Toggle hidden files", {
    description: "Show or hide hidden files in the focused Files location.",
    category: "Files",
    scope: "tool:files",
    mac: "Cmd+Shift+Period",
    windows: "Ctrl+Shift+Period",
  }),
  command("explorer.preview.toggle", "Toggle Files preview", {
    description: "Show or hide the preview panel in Files.",
    category: "Files",
    scope: "tool:files",
  }),
  command("explorer.preview_save", "Save preview changes", {
    description: "Save edits made in the Files preview.",
    category: "Files",
    scope: "tool:files",
    mac: "Cmd+S",
    windows: "Ctrl+S",
    allowInEditable: true,
  }),
  command("explorer.sidebar.toggle", "Toggle Files sidebar", {
    description: "Show or hide the sidebar in Files.",
    category: "Files",
    scope: "tool:files",
  }),
];
