import type { ShortcutBindingPair, ShortcutCommandDefinition, ShortcutPlatform } from "./types";
import { command } from "./factory";
import { filesShortcutCommands } from "./filesCommands";
import { roadmapShortcutCommands } from "./roadmapCommands";
export type * from "./types";

const shellCommands: ShortcutCommandDefinition[] = [
  command("search.toggle", "Open Misty", {
    description: "Search Misty, open tools, or ask a question.",
    category: "Misty",
    aliases: ["launcher", "search", "ask"],
    mac: "Cmd+K",
    windows: "Ctrl+K",
    allowInEditable: true,
    nativeMenu: true,
    allowShadowing: true,
  }),
  command("app.command_palette", "Open command palette", {
    description: "Open Misty with command-only results.",
    category: "Misty",
    aliases: ["actions", "commands", "launcher"],
    mac: "Cmd+Shift+P",
    windows: "Ctrl+Shift+P",
    allowInEditable: true,
    nativeMenu: true,
    allowShadowing: true,
  }),
  command("app.open_settings", "Open settings", {
    description: "Open Misty settings.",
    category: "Misty",
    aliases: ["preferences", "configuration"],
    mac: "Cmd+Comma",
    windows: "Ctrl+Comma",
    allowInEditable: true,
    nativeMenu: true,
  }),
  command("app.toggle_navigator", "Toggle navigator", {
    description: "Show or hide the global navigator.",
    category: "View",
    aliases: ["sidebar", "navigation"],
    mac: "Cmd+Shift+B",
    windows: "Ctrl+Shift+B",
    allowInEditable: true,
    nativeMenu: true,
  }),
  command("app.zoom_in", "Zoom in", {
    description: "Increase the app interface scale.",
    category: "View",
    mac: "Cmd+Plus",
    windows: "Ctrl+Plus",
    allowInEditable: true,
    repeatable: true,
    nativeMenu: true,
  }),
  command("app.zoom_out", "Zoom out", {
    description: "Decrease the app interface scale.",
    category: "View",
    mac: "Cmd+Minus",
    windows: "Ctrl+Minus",
    allowInEditable: true,
    repeatable: true,
    nativeMenu: true,
  }),
  command("app.zoom_reset", "Reset zoom", {
    description: "Return the app interface to its default scale.",
    category: "View",
    mac: "Cmd+0",
    windows: "Ctrl+0",
    allowInEditable: true,
    nativeMenu: true,
  }),
];

const workspaceCommands: ShortcutCommandDefinition[] = [
  command("workspace.new_virtual_window", "New virtual window", {
    description: "Create a full workspace window inside the active Space.",
    category: "Virtual windows",
    scope: "workspace",
    aliases: ["new workspace", "new window"],
    mac: "Cmd+N",
    windows: "Ctrl+N",
    allowInEditable: true,
    nativeMenu: true,
  }),
  command("workspace.close_virtual_window", "Close virtual window", {
    description: "Close the active virtual window when another window remains.",
    category: "Virtual windows",
    scope: "workspace",
    aliases: ["close workspace", "close window"],
    mac: "Cmd+Shift+W",
    windows: "Ctrl+Shift+W",
    allowInEditable: true,
    nativeMenu: true,
  }),
  command("workspace.next_virtual_window", "Next virtual window", {
    description: "Switch to the next virtual window in this Space.",
    category: "Virtual windows",
    scope: "workspace",
    mac: "Cmd+Grave",
    windows: "Ctrl+Alt+Grave",
    windowsAlternate: "Ctrl+Shift+PageDown",
    allowInEditable: true,
    nativeMenu: true,
  }),
  command("workspace.previous_virtual_window", "Previous virtual window", {
    description: "Switch to the previous virtual window in this Space.",
    category: "Virtual windows",
    scope: "workspace",
    mac: "Cmd+Shift+Grave",
    windows: "Ctrl+Alt+Shift+Grave",
    windowsAlternate: "Ctrl+Shift+PageUp",
    allowInEditable: true,
    nativeMenu: true,
  }),
  command("workspace.reopen_virtual_window", "Reopen closed virtual window", {
    description: "Restore the most recently closed virtual window in this Space.",
    category: "Virtual windows",
    scope: "workspace",
    aliases: ["undo close window", "restore workspace"],
    mac: "Cmd+Option+Shift+W",
    windows: "Ctrl+Alt+Shift+W",
    allowInEditable: true,
    nativeMenu: true,
  }),
  ...Array.from({ length: 9 }, (_, index) => {
    const number = index + 1;
    return command(`workspace.window_${number}`, `Select virtual window ${number}`, {
      description: `Switch directly to virtual window ${number} in this Space.`,
      category: "Virtual windows",
      scope: "workspace",
      aliases: [`window ${number}`, `workspace ${number}`],
      mac: `Option+${number}`,
      windows: `Ctrl+Alt+${number}`,
      allowInEditable: true,
    });
  }),
  command("workspace.swap_panel_next", "Swap panel with next", {
    description: "Swap the focused panel's complete tab group with the next panel.",
    category: "Virtual windows",
    scope: "workspace",
    aliases: ["reorder panels", "move panel"],
  }),
  command("workspace.new_tab", "New tab", {
    description: "Open the keyboard-first New Tab picker.",
    category: "Tabs and panes",
    scope: "workspace",
    aliases: ["add tab", "tool picker"],
    mac: "Cmd+T",
    windows: "Ctrl+T",
    allowInEditable: true,
    nativeMenu: true,
  }),
  command("workspace.close_tab", "Close tab", {
    description: "Close the active tab in the focused pane.",
    category: "Tabs and panes",
    scope: "workspace",
    mac: "Cmd+W",
    windows: "Ctrl+W",
    allowInEditable: true,
    nativeMenu: true,
  }),
  command("workspace.reopen_tab", "Reopen closed tab", {
    description: "Restore the most recently closed tab in the focused pane.",
    category: "Tabs and panes",
    scope: "workspace",
    mac: "Cmd+Shift+T",
    windows: "Ctrl+Shift+T",
    allowInEditable: true,
    nativeMenu: true,
  }),
  command("workspace.next_tab", "Next tab", {
    description: "Move to the next tab in the focused pane, wrapping at the end.",
    category: "Tabs and panes",
    scope: "workspace",
    mac: "Cmd+Shift+RightBracket",
    macAlternate: "Ctrl+Tab",
    windows: "Ctrl+Tab",
    windowsAlternate: "Ctrl+PageDown",
    allowInEditable: true,
    repeatable: true,
    nativeMenu: true,
  }),
  command("workspace.previous_tab", "Previous tab", {
    description: "Move to the previous tab in the focused pane, wrapping at the start.",
    category: "Tabs and panes",
    scope: "workspace",
    mac: "Cmd+Shift+LeftBracket",
    macAlternate: "Ctrl+Shift+Tab",
    windows: "Ctrl+Shift+Tab",
    windowsAlternate: "Ctrl+PageUp",
    allowInEditable: true,
    repeatable: true,
    nativeMenu: true,
  }),
  command("workspace.focus_pane_left", "Focus pane left", {
    description: "Move focus to the pane on the left.",
    category: "Tabs and panes",
    scope: "workspace",
    mac: "Option+H",
    windows: "Alt+H",
    allowInEditable: true,
  }),
  command("workspace.focus_pane_right", "Focus pane right", {
    description: "Move focus to the pane on the right.",
    category: "Tabs and panes",
    scope: "workspace",
    mac: "Option+L",
    windows: "Alt+L",
    allowInEditable: true,
  }),
  command("workspace.focus_pane_up", "Focus pane above", {
    description: "Move focus to the pane above.",
    category: "Tabs and panes",
    scope: "workspace",
    mac: "Option+K",
    windows: "Alt+K",
    allowInEditable: true,
  }),
  command("workspace.focus_pane_down", "Focus pane below", {
    description: "Move focus to the pane below.",
    category: "Tabs and panes",
    scope: "workspace",
    mac: "Option+J",
    windows: "Alt+J",
    allowInEditable: true,
  }),
  command("workspace.split_right", "Split pane right", {
    description: "Create a pane to the right of the focused pane.",
    category: "Tabs and panes",
    scope: "workspace",
  }),
  command("workspace.split_down", "Split pane below", {
    description: "Create a pane below the focused pane.",
    category: "Tabs and panes",
    scope: "workspace",
  }),
  command("workspace.close_pane", "Close focused pane", {
    description: "Close the focused pane and move its tabs into another pane.",
    category: "Tabs and panes",
    scope: "workspace",
  }),
  command("navigation.back", "Go back", {
    description: "Go back in the focused tool, then Misty navigation history.",
    category: "Navigation",
    scope: "workspace",
    mac: "Cmd+LeftBracket",
    windows: "Alt+ArrowLeft",
    allowInEditable: true,
    repeatable: true,
  }),
  command("navigation.forward", "Go forward", {
    description: "Go forward in the focused tool, then Misty navigation history.",
    category: "Navigation",
    scope: "workspace",
    mac: "Cmd+RightBracket",
    windows: "Alt+ArrowRight",
    allowInEditable: true,
    repeatable: true,
  }),
  command("navigation.refresh", "Refresh focused tool", {
    description: "Refresh the focused tool without reloading the Misty window.",
    category: "Navigation",
    scope: "workspace",
    mac: "Cmd+R",
    windows: "Ctrl+R",
    allowInEditable: true,
    nativeMenu: true,
    allowShadowing: true,
  }),
  command("tool.terminal", "Open or focus Terminal", {
    description: "Focus the last Terminal tab or open one in the focused pane.",
    category: "Jump to tool",
    scope: "workspace",
    aliases: ["shell", "console"],
    mac: "Cmd+J",
    windows: "Ctrl+Grave",
    allowInEditable: true,
  }),
];

const toolSlots = [
  ["home", "Home"],
  ["journal", "Journal"],
  ["planner", "Planner"],
  ["chat", "Chat"],
  ["inbox", "Inbox"],
  ["library", "Library"],
  ["browser", "Browser"],
  ["files", "Files"],
  ["code", "Code"],
] as const;

const tabAndToolCommands = [
  ...Array.from({ length: 9 }, (_, index) =>
    command(
      `workspace.tab_${index + 1}`,
      index === 8 ? "Select last tab" : `Select tab ${index + 1}`,
      {
        description:
          index === 8
            ? "Select the last tab in the focused pane."
            : `Select tab ${index + 1} in the focused pane.`,
        category: "Tabs and panes",
        scope: "workspace",
        mac: `Cmd+${index + 1}`,
        windows: `Ctrl+${index + 1}`,
        allowInEditable: true,
      },
    ),
  ),
  ...toolSlots.map(([id, label], index) =>
    command(`tool.${id}`, `Open or focus ${label}`, {
      description: `Focus the last ${label} tab or open one in the focused pane.`,
      category: "Jump to tool",
      scope: "workspace",
      aliases: ["jump", "switch tool", label.toLowerCase()],
      mac: `Cmd+Shift+${index + 1}`,
      windows: `Ctrl+Shift+${index + 1}`,
      allowInEditable: true,
    }),
  ),
];

const toolCommands: ShortcutCommandDefinition[] = [
  command("code.quick_open", "Quick open file", {
    description: "Find and open a file in Code.",
    category: "Code",
    scope: "tool:code",
    mac: "Cmd+P",
    windows: "Ctrl+P",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("code.command_palette", "Code command palette", {
    description: "Show actions for the focused Code tab.",
    category: "Code",
    scope: "tool:code",
    mac: "Cmd+Shift+P",
    windows: "Ctrl+Shift+P",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("code.search_project", "Search project", {
    description: "Search across files in the current project.",
    category: "Code",
    scope: "tool:code",
    mac: "Cmd+Shift+F",
    windows: "Ctrl+Shift+F",
    allowInEditable: true,
  }),
  command("code.harpoon", "Open Harpoon", {
    description: "Open the fast file navigation list.",
    category: "Code",
    scope: "tool:code",
    aliases: ["file marks", "jump list"],
    mac: "Cmd+Shift+E",
    windows: "Ctrl+E",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("code.previous_file", "Previous Code file", {
    description: "Return to the previously focused file.",
    category: "Code",
    scope: "tool:code",
    mac: "Cmd+Option+O",
    windows: "Alt+O",
    allowInEditable: true,
  }),
  command("code.toggle_explorer", "Toggle Code explorer", {
    description: "Show or hide the file explorer in Code.",
    category: "Code",
    scope: "tool:code",
    mac: "Cmd+B",
    windows: "Ctrl+B",
    allowInEditable: true,
  }),
  command("code.toggle_terminal", "Toggle Code Terminal", {
    description: "Show or hide the Terminal attached to the focused Code tab.",
    category: "Code",
    scope: "tool:code",
    mac: "Cmd+J",
    windows: "Ctrl+Grave",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("code.save", "Save Code file", {
    description: "Save the active file.",
    category: "Code",
    scope: "tool:code",
    mac: "Cmd+S",
    windows: "Ctrl+S",
    allowInEditable: true,
  }),
  command("code.inline_ai", "Edit Code with AI", {
    description: "Open an inline AI request for the current Code selection.",
    category: "Code",
    scope: "tool:code",
    mac: "Cmd+K",
    windows: "Ctrl+K",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("code.apply_inline_ai", "Apply inline AI edit", {
    description: "Apply the current inline AI preview.",
    category: "Code",
    scope: "tool:code",
    mac: "Cmd+Enter",
    windows: "Ctrl+Enter",
    allowInEditable: true,
  }),
  command("code.open_multibuffer_excerpt", "Open result in new tab", {
    description: "Open the selected Code result excerpts in new tabs.",
    category: "Code",
    scope: "tool:code",
    mac: "Option+Enter",
    windows: "Alt+Enter",
    allowInEditable: true,
  }),
  command("code.go_to_definition", "Go to definition", {
    description: "Open the definition under the cursor.",
    category: "Code",
    scope: "tool:code",
    mac: "F12",
    allowInEditable: true,
  }),
  command("code.show_hover", "Show symbol information", {
    description: "Show language information for the symbol under the cursor.",
    category: "Code",
    scope: "tool:code",
    mac: "Cmd+Shift+I",
    windows: "Ctrl+Shift+I",
    allowInEditable: true,
  }),
  command("code.format_document", "Format Code document", {
    description: "Format the active Code document.",
    category: "Code",
    scope: "tool:code",
    mac: "Option+Shift+F",
    windows: "Alt+Shift+F",
    allowInEditable: true,
  }),
  command("code.references", "Find Code references", {
    description: "Find every reference to the symbol under the cursor.",
    category: "Code",
    scope: "tool:code",
    mac: "Shift+F12",
    allowInEditable: true,
  }),
  command("code.rename", "Rename Code symbol", {
    description: "Rename the symbol under the cursor across the project.",
    category: "Code",
    scope: "tool:code",
    mac: "F2",
    allowInEditable: true,
  }),
  command("code.code_actions", "Show Code actions", {
    description: "Show fixes and refactors for the current selection.",
    category: "Code",
    scope: "tool:code",
    mac: "Cmd+Period",
    windows: "Ctrl+Period",
    allowInEditable: true,
  }),
  command("code.document_symbols", "Show document symbols", {
    description: "Navigate headings, functions, and symbols in the active file.",
    category: "Code",
    scope: "tool:code",
    mac: "Cmd+Shift+O",
    windows: "Ctrl+Shift+O",
    allowInEditable: true,
  }),
  command("code.select_next_occurrence", "Select next occurrence", {
    description: "Add the next matching occurrence to the Code selection.",
    category: "Code",
    scope: "tool:code",
    mac: "Cmd+D",
    windows: "Ctrl+D",
    allowInEditable: true,
    repeatable: true,
  }),
  command("code.select_all_occurrences", "Select all occurrences", {
    description: "Select every matching occurrence in the Code editor.",
    category: "Code",
    scope: "tool:code",
    mac: "Cmd+Shift+L",
    windows: "Ctrl+Shift+L",
    allowInEditable: true,
  }),
  command("code.add_cursor_above", "Add Code cursor above", {
    description: "Add another editor cursor on the line above.",
    category: "Code",
    scope: "tool:code",
    mac: "Cmd+Option+ArrowUp",
    windows: "Ctrl+Alt+ArrowUp",
    allowInEditable: true,
    repeatable: true,
  }),
  command("code.add_cursor_below", "Add Code cursor below", {
    description: "Add another editor cursor on the line below.",
    category: "Code",
    scope: "tool:code",
    mac: "Cmd+Option+ArrowDown",
    windows: "Ctrl+Alt+ArrowDown",
    allowInEditable: true,
    repeatable: true,
  }),
  command("code.undo_selection", "Undo Code selection", {
    description: "Undo the last multiple-selection change.",
    category: "Code",
    scope: "tool:code",
    mac: "Cmd+U",
    windows: "Ctrl+U",
    allowInEditable: true,
  }),
  ...Array.from({ length: 4 }, (_, index) =>
    command(`code.mark_${index + 1}`, `Open Harpoon slot ${index + 1}`, {
      description: `Open the file saved in Harpoon slot ${index + 1}.`,
      category: "Code",
      scope: "tool:code",
      mac: `Cmd+Option+${index + 1}`,
      windows: `Alt+${index + 1}`,
      allowInEditable: true,
    }),
  ),
  command("terminal.clear", "Clear Terminal", {
    description: "Clear the focused Terminal while preserving shell history.",
    category: "Terminal",
    scope: "tool:terminal",
    mac: "Cmd+K",
    windows: "Ctrl+K",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("terminal.search", "Search Terminal", {
    description: "Find text in the focused Terminal.",
    category: "Terminal",
    scope: "tool:terminal",
    mac: "Cmd+F",
    windows: "Ctrl+F",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("terminal.zoom_in", "Increase Terminal font size", {
    description: "Increase the font size in the focused Terminal.",
    category: "Terminal",
    scope: "tool:terminal",
    mac: "Cmd+Plus",
    windows: "Ctrl+Plus",
    allowInEditable: true,
    repeatable: true,
    allowShadowing: true,
  }),
  command("terminal.zoom_out", "Decrease Terminal font size", {
    description: "Decrease the font size in the focused Terminal.",
    category: "Terminal",
    scope: "tool:terminal",
    mac: "Cmd+Minus",
    windows: "Ctrl+Minus",
    allowInEditable: true,
    repeatable: true,
    allowShadowing: true,
  }),
  command("terminal.zoom_reset", "Reset Terminal font size", {
    description: "Restore the default font size in the focused Terminal.",
    category: "Terminal",
    scope: "tool:terminal",
    mac: "Cmd+0",
    windows: "Ctrl+0",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("terminal.copy", "Copy Terminal selection", {
    description: "Copy selected text from the focused Terminal.",
    category: "Terminal",
    scope: "tool:terminal",
    mac: "Cmd+Shift+C",
    windows: "Ctrl+Shift+C",
    allowInEditable: true,
  }),
  command("terminal.paste", "Paste into Terminal", {
    description: "Paste clipboard text into the focused Terminal.",
    category: "Terminal",
    scope: "tool:terminal",
    mac: "Cmd+V",
    windows: "Ctrl+V",
    allowInEditable: true,
  }),
  ...filesShortcutCommands,
  command("planner.create", "Create Planner item", {
    description: "Create an item in the focused Planner view.",
    category: "Planner",
    scope: "tool:planner",
    mac: "C",
    windows: "C",
  }),
  ...roadmapShortcutCommands,
  command("library.copy", "Copy Library selection", {
    description: "Copy the selected Library content.",
    category: "Library",
    scope: "tool:library",
    mac: "Cmd+C",
    windows: "Ctrl+C",
  }),
  command("browser.annotation_undo", "Undo Browser annotation", {
    description: "Undo the last annotation edit in Browser.",
    category: "Browser",
    scope: "tool:browser",
    mac: "Cmd+Z",
    windows: "Ctrl+Z",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("browser.annotation_redo", "Redo Browser annotation", {
    description: "Redo the last annotation edit in Browser.",
    category: "Browser",
    scope: "tool:browser",
    mac: "Cmd+Shift+Z",
    windows: "Ctrl+Y",
    allowInEditable: true,
    allowShadowing: true,
  }),
];

export const shortcutCommandRegistry: ShortcutCommandDefinition[] = [
  ...shellCommands,
  ...workspaceCommands,
  ...tabAndToolCommands,
  ...toolCommands,
];

export const shortcutCommandsById = new Map(
  shortcutCommandRegistry.map((definition) => [definition.id, definition]),
);

export function registerShortcutCommandDefinition(
  definition: ShortcutCommandDefinition,
): () => void {
  const existing = shortcutCommandsById.get(definition.id);
  if (existing) return () => undefined;
  shortcutCommandRegistry.push(definition);
  shortcutCommandsById.set(definition.id, definition);
  return () => {
    const index = shortcutCommandRegistry.indexOf(definition);
    if (index >= 0) shortcutCommandRegistry.splice(index, 1);
    if (shortcutCommandsById.get(definition.id) === definition)
      shortcutCommandsById.delete(definition.id);
  };
}

export function defaultBindingsFor(
  definition: ShortcutCommandDefinition,
  platform: ShortcutPlatform,
): ShortcutBindingPair {
  return definition.defaults[platform];
}
