/** Human-readable review text; retain unknown permission names for honest disclosure. */
export function permissionLabel(permission: string): string {
  const labels: Record<string, string> = {
    storage: "Save extension settings",
    activeTab: "Access the current page when you use the extension",
    tabs: "Read browser tab titles and addresses",
    scripting: "Run extension scripts on permitted websites",
    nativeMessaging: "Connect to an installed companion application",
    cookies: "Access cookies on permitted websites",
    clipboardWrite: "Write to your clipboard",
    clipboardRead: "Read your clipboard",
    downloads: "Manage downloads",
    notifications: "Show notifications",
    contextMenus: "Add context-menu actions",
    menus: "Add context-menu actions",
    alarms: "Schedule extension tasks",
    idle: "Detect when you are away from your computer",
    history: "Read and delete your browsing history",
    topSites: "Read your most visited sites",
    bookmarks: "Read bookmarks (not shared with extensions yet)",
    sessions: "See and reopen recently closed tabs",
    search: "Search with your default search engine",
    browsingData: "Clear browsing history, downloads, cookies and site data",
    find: "Search text on the current page",
    tts: "Read text aloud",
    privacy: "Read privacy settings",
    management: "Read its own extension details",
    identity: "Sign in to websites through a sign-in tab",
    webRequestBlocking: "Block or change website requests (repeat requests only in Misty)",
    tabHide: "Hide tabs (not available in Misty)",
    contextualIdentities: "Use Firefox containers (not available in Misty)",
    theme: "Change the browser theme (not available in Misty)",
    webRequest: "Observe requests on permitted websites",
    webNavigation: "Observe navigation on permitted websites",
    declarativeNetRequest: "Block or modify website requests using extension rules",
    declarativeNetRequestWithHostAccess: "Block or modify requests on permitted websites",
    unlimitedStorage: "Store extension data without the usual local size limit",
    "<all_urls>": "Read and change data on all websites",
  };
  return labels[permission] ?? permission;
}
