import {
  Mail,
  MessagesSquare,
  NotebookPen,
  Calendar,
  Library,
  Globe,
  Folder,
  Inbox,
  Star,
  Heart,
  Bookmark,
  Briefcase,
  House,
  Building,
  School,
  GraduationCap,
  BookOpen,
  FileText,
  Newspaper,
  Pencil,
  Palette,
  Camera,
  Image,
  Film,
  Music,
  Headphones,
  Radio,
  Mic,
  Video,
  Tv,
  Play,
  Gamepad2,
  Trophy,
  Medal,
  Target,
  Flag,
  Compass,
  Map,
  MapPin,
  Plane,
  Train,
  Car,
  Bike,
  Ship,
  Mountain,
  TreePine,
  Flower,
  Sun,
  Moon,
  Cloud,
  Umbrella,
  Coffee,
  Utensils,
  Cake,
  ShoppingBag,
  ShoppingCart,
  Gift,
  Wallet,
  CreditCard,
  Landmark,
  ChartBar,
  Calculator,
  Code,
  Terminal,
  Laptop,
  Monitor,
  Smartphone,
  Wifi,
  Database,
  Server,
  Shield,
  Lock,
  Key,
  Wrench,
  Settings,
  Lightbulb,
  Zap,
  Rocket,
  Atom,
  FlaskConical,
  Stethoscope,
  Dumbbell,
  PawPrint,
  Users,
  User,
  Bell,
  Clock,
  Check,
  Circle,
  Hash,
  type LucideIcon,
} from "lucide-react";
export const groupIcons: Record<string, LucideIcon> = {
  mail: Mail,
  messages: MessagesSquare,
  notebook: NotebookPen,
  calendar: Calendar,
  library: Library,
  globe: Globe,
  folder: Folder,
  inbox: Inbox,
  star: Star,
  heart: Heart,
  bookmark: Bookmark,
  briefcase: Briefcase,
  house: House,
  building: Building,
  school: School,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  "file-text": FileText,
  newspaper: Newspaper,
  pencil: Pencil,
  palette: Palette,
  camera: Camera,
  image: Image,
  film: Film,
  music: Music,
  headphones: Headphones,
  radio: Radio,
  mic: Mic,
  video: Video,
  tv: Tv,
  play: Play,
  gamepad2: Gamepad2,
  trophy: Trophy,
  medal: Medal,
  target: Target,
  flag: Flag,
  compass: Compass,
  map: Map,
  "map-pin": MapPin,
  plane: Plane,
  train: Train,
  car: Car,
  bike: Bike,
  ship: Ship,
  mountain: Mountain,
  "tree-pine": TreePine,
  flower: Flower,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  umbrella: Umbrella,
  coffee: Coffee,
  utensils: Utensils,
  cake: Cake,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  gift: Gift,
  wallet: Wallet,
  "credit-card": CreditCard,
  landmark: Landmark,
  "chart-bar": ChartBar,
  calculator: Calculator,
  code: Code,
  terminal: Terminal,
  laptop: Laptop,
  monitor: Monitor,
  smartphone: Smartphone,
  wifi: Wifi,
  database: Database,
  server: Server,
  shield: Shield,
  lock: Lock,
  key: Key,
  wrench: Wrench,
  settings: Settings,
  lightbulb: Lightbulb,
  zap: Zap,
  rocket: Rocket,
  atom: Atom,
  "flask-conical": FlaskConical,
  stethoscope: Stethoscope,
  dumbbell: Dumbbell,
  "paw-print": PawPrint,
  users: Users,
  user: User,
  bell: Bell,
  clock: Clock,
  check: Check,
  circle: Circle,
  hash: Hash,
};
export function GroupIcon({ name, size = 18 }: { name: string; size?: number }) {
  const Icon = groupIcons[name] ?? Globe;
  return <Icon size={size} aria-hidden="true" className="shrink-0 size-[18px]" />;
}
