import type { ShortcutBindingPair, ShortcutCommandDefinition, ShortcutPlatform } from "./types";
import { command } from "./factory";
import { filesShortcutCommands } from "./filesCommands";
import { roadmapShortcutCommands } from "./roadmapCommands";
export type * from "./types";
const shellCommands: ShortcutCommandDefinition[] = [
  command("search.toggle", "Search", {
    description: "Search Google or open a web address in your workspace.",
    category: "Navigation",
    aliases: ["search", "url", "website", "google"],
    mac: "Cmd+K",
    windows: "Ctrl+K",
    allowInEditable: true,
    nativeMenu: true,
    allowShadowing: true,
  }),
  command("browser.edit_address", "Edit current address", {
    description: "Reveal the focused website’s address for navigation.",
    category: "Navigation",
    scope: "tool:browser",
    mac: "Cmd+L",
    windows: "Ctrl+L",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("misty.contextual_companion", "Open Misty", {
    description: "Open Misty in the current window.",
    category: "Misty",
    aliases: ["assistant", "ask misty"],
    mac: "Cmd+Shift+K",
    windows: "Ctrl+Shift+K",
    allowInEditable: true,
    nativeMenu: false,
    allowShadowing: true,
  }),
  command("app.command_palette", "Open command palette", {
    description: "Open Misty with command-only results.",
    category: "Misty",
    aliases: ["actions", "commands", "launcher"],
    mac: "Cmd+Shift+P",
    windows: "Ctrl+Shift+P",
    allowInEditable: true,
    nativeMenu: true,
    allowShadowing: true,
  }),
  command("app.open_settings", "Open settings", {
    description: "Open Misty settings.",
    category: "Misty",
    aliases: ["preferences", "configuration"],
    mac: "Cmd+Comma",
    windows: "Ctrl+Comma",
    allowInEditable: true,
    nativeMenu: true,
  }),
  command("app.toggle_navigator", "Toggle navigation auto-hide", {
    description: "Switch between an always-visible icon rail and edge-hover auto-hide.",
    category: "View",
    aliases: ["sidebar", "navigation"],
    mac: "Cmd+Shift+B",
    windows: "Ctrl+Shift+B",
    allowInEditable: true,
    nativeMenu: true,
  }),
  command("app.zoom_in", "Zoom in", {
    description: "Increase the app interface scale.",
    category: "View",
    mac: "Cmd+Plus",
    macAlternate: "Ctrl+Plus",
    windows: "Ctrl+Plus",
    allowInEditable: true,
    repeatable: true,
    nativeMenu: true,
  }),
  command("app.zoom_out", "Zoom out", {
    description: "Decrease the app interface scale.",
    category: "View",
    mac: "Cmd+Minus",
    macAlternate: "Ctrl+Minus",
    windows: "Ctrl+Minus",
    allowInEditable: true,
    repeatable: true,
    nativeMenu: true,
  }),
  command("app.zoom_reset", "Reset zoom", {
    description: "Return the app interface to its default scale.",
    category: "View",
    mac: "Cmd+0",
    macAlternate: "Ctrl+0",
    windows: "Ctrl+0",
    allowInEditable: true,
    nativeMenu: true,
  }),
];

const workspaceCommands: ShortcutCommandDefinition[] = [
  command("workspace.new_virtual_window", "New virtual window", {
    description: "Create a full workspace window inside the active Space.",
    category: "Virtual windows",
    scope: "workspace",
    aliases: ["new workspace", "new window"],
    mac: "Cmd+N",
    windows: "Ctrl+N",
    allowInEditable: true,
    nativeMenu: true,
  }),
  command("workspace.close_virtual_window", "Close virtual window", {
    description: "Close the active virtual window when another window remains.",
    category: "Virtual windows",
    scope: "workspace",
    aliases: ["close workspace", "close window"],
    mac: "Cmd+Shift+W",
    windows: "Ctrl+Shift+W",
    allowInEditable: true,
    nativeMenu: true,
  }),
  command("workspace.next_virtual_window", "Next virtual window", {
    description: "Switch to the next virtual window in this Space.",
    category: "Virtual windows",
    scope: "workspace",
    mac: "Cmd+Grave",
    windows: "Ctrl+Alt+Grave",
    windowsAlternate: "Ctrl+Shift+PageDown",
    allowInEditable: true,
    nativeMenu: true,
  }),
  command("workspace.previous_virtual_window", "Previous virtual window", {
    description: "Switch to the previous virtual window in this Space.",
    category: "Virtual windows",
    scope: "workspace",
    mac: "Cmd+Shift+Grave",
    windows: "Ctrl+Alt+Shift+Grave",
    windowsAlternate: "Ctrl+Shift+PageUp",
    allowInEditable: true,
    nativeMenu: true,
  }),
  command("workspace.reopen_virtual_window", "Reopen closed virtual window", {
    description: "Restore the most recently closed virtual window in this Space.",
    category: "Virtual windows",
    scope: "workspace",
    aliases: ["undo close window", "restore workspace"],
    mac: "Cmd+Option+Shift+W",
    windows: "Ctrl+Alt+Shift+W",
    allowInEditable: true,
    nativeMenu: true,
  }),
  ...Array.from({ length: 9 }, (_, index) => {
    const number = index + 1;
    return command(`workspace.window_${number}`, `Select virtual window ${number}`, {
      description: `Switch directly to virtual window ${number} in this Space.`,
      category: "Virtual windows",
      scope: "workspace",
      aliases: [`window ${number}`, `workspace ${number}`],
      mac: `Option+${number}`,
      windows: `Ctrl+Alt+${number}`,
      allowInEditable: true,
    });
  }),
  command("workspace.swap_panel_next", "Swap panel with next", {
    description: "Swap the focused panel's complete tab group with the next panel.",
    category: "Virtual windows",
    scope: "workspace",
    aliases: ["reorder panels", "move panel"],
  }),
  command("workspace.new_tab", "New tab", {
    description: "Open the keyboard-first New Tab picker.",
    category: "Tabs and panes",
    scope: "workspace",
    aliases: ["add tab", "tool picker"],
    mac: "Cmd+T",
    windows: "Ctrl+T",
    allowInEditable: true,
    nativeMenu: true,
  }),
  command("workspace.close_tab", "Close tab", {
    description: "Close the active tab in the focused pane.",
    category: "Tabs and panes",
    scope: "workspace",
    mac: "Cmd+W",
    windows: "Ctrl+W",
    allowInEditable: true,
    nativeMenu: true,
  }),
  command("workspace.reopen_tab", "Reopen closed tab", {
    description: "Restore the most recently closed tab in the focused pane.",
    category: "Tabs and panes",
    scope: "workspace",
    mac: "Cmd+Shift+T",
    windows: "Ctrl+Shift+T",
    allowInEditable: true,
    nativeMenu: true,
  }),
  command("workspace.next_tab", "Next tab", {
    description: "Move to the next tab in the focused pane, wrapping at the end.",
    category: "Tabs and panes",
    scope: "workspace",
    mac: "Cmd+Shift+RightBracket",
    macAlternate: "Ctrl+Tab",
    windows: "Ctrl+Tab",
    windowsAlternate: "Ctrl+PageDown",
    allowInEditable: true,
    repeatable: true,
    nativeMenu: true,
  }),
  command("workspace.previous_tab", "Previous tab", {
    description: "Move to the previous tab in the focused pane, wrapping at the start.",
    category: "Tabs and panes",
    scope: "workspace",
    mac: "Cmd+Shift+LeftBracket",
    macAlternate: "Ctrl+Shift+Tab",
    windows: "Ctrl+Shift+Tab",
    windowsAlternate: "Ctrl+PageUp",
    allowInEditable: true,
    repeatable: true,
    nativeMenu: true,
  }),
  command("workspace.focus_pane_left", "Focus pane left", {
    description: "Move focus to the pane on the left.",
    category: "Tabs and panes",
    scope: "workspace",
    mac: "Option+H",
    windows: "Alt+H",
    allowInEditable: true,
  }),
  command("workspace.focus_pane_right", "Focus pane right", {
    description: "Move focus to the pane on the right.",
    category: "Tabs and panes",
    scope: "workspace",
    mac: "Option+L",
    windows: "Alt+L",
    allowInEditable: true,
  }),
  command("workspace.focus_pane_up", "Focus pane above", {
    description: "Move focus to the pane above.",
    category: "Tabs and panes",
    scope: "workspace",
    mac: "Option+K",
    windows: "Alt+K",
    allowInEditable: true,
  }),
  command("workspace.focus_pane_down", "Focus pane below", {
    description: "Move focus to the pane below.",
    category: "Tabs and panes",
    scope: "workspace",
    mac: "Option+J",
    windows: "Alt+J",
    allowInEditable: true,
  }),
  command("workspace.split_right", "Split pane right", {
    description: "Create a pane to the right of the focused pane.",
    category: "Tabs and panes",
    scope: "workspace",
  }),
  command("workspace.split_down", "Split pane below", {
    description: "Create a pane below the focused pane.",
    category: "Tabs and panes",
    scope: "workspace",
  }),
  command("workspace.close_pane", "Close focused pane", {
    description: "Close the focused pane and move its tabs into another pane.",
    category: "Tabs and panes",
    scope: "workspace",
  }),
  command("navigation.back", "Go back", {
    description: "Go back in the focused tool.",
    category: "Navigation",
    scope: "workspace",
    mac: "Cmd+LeftBracket",
    windows: "Alt+ArrowLeft",
    allowInEditable: true,
    repeatable: true,
  }),
  command("navigation.forward", "Go forward", {
    description: "Go forward in the focused tool.",
    category: "Navigation",
    scope: "workspace",
    mac: "Cmd+RightBracket",
    windows: "Alt+ArrowRight",
    allowInEditable: true,
    repeatable: true,
  }),
  command("navigation.refresh", "Refresh focused tool", {
    description: "Refresh the focused tool without reloading the Misty window.",
    category: "Navigation",
    scope: "workspace",
    mac: "Cmd+R",
    windows: "Ctrl+R",
    allowInEditable: true,
    nativeMenu: true,
    allowShadowing: true,
  }),
  command("tool.terminal", "Open or focus Terminal", {
    description: "Focus the last Terminal tab or open one in the focused pane.",
    category: "Jump to tool",
    scope: "workspace",
    aliases: ["shell", "console"],
    mac: "Cmd+J",
    windows: "Ctrl+Grave",
    allowInEditable: true,
  }),
];

// Each tool keeps its Cmd/Ctrl+Shift number; 1 belonged to the retired Home page.
const toolSlots = [
  ["journal", "Journal", 2],
  ["planner", "Planner", 3],
  ["social", "Social", 4],
  ["library", "Library", 5],
  ["browser", "Browser", 6],
  ["files", "Files", 7],
  ["code", "Code", 8],
] as const;

const tabAndToolCommands = [
  ...Array.from({ length: 9 }, (_, index) =>
    command(
      `workspace.tab_${index + 1}`,
      index === 8 ? "Select last tab" : `Select tab ${index + 1}`,
      {
        description:
          index === 8
            ? "Select the last tab in the focused pane."
            : `Select tab ${index + 1} in the focused pane.`,
        category: "Tabs and panes",
        scope: "workspace",
        mac: `Cmd+${index + 1}`,
        windows: `Ctrl+${index + 1}`,
        allowInEditable: true,
      },
    ),
  ),
  ...toolSlots.map(([id, label, slot]) =>
    command(`tool.${id}`, `Open or focus ${label}`, {
      description: `Focus the last ${label} tab or open one in the focused pane.`,
      category: "Jump to tool",
      scope: "workspace",
      aliases: ["jump", "switch tool", label.toLowerCase()],
      mac: `Cmd+Shift+${slot}`,
      windows: `Ctrl+Shift+${slot}`,
      allowInEditable: true,
    }),
  ),
];

const toolCommands: ShortcutCommandDefinition[] = [
  ...filesShortcutCommands,
  command("planner.create", "Create Planner item", {
    description: "Create an item in the focused Planner view.",
    category: "Planner",
    scope: "tool:planner",
    mac: "C",
    windows: "C",
  }),
  ...roadmapShortcutCommands,
  command("library.copy", "Copy Library selection", {
    description: "Copy the selected Library content.",
    category: "Library",
    scope: "tool:library",
    mac: "Cmd+C",
    windows: "Ctrl+C",
  }),
  command("browser.new_private_tab", "New private tab", {
    description: "Browse without saving history, cookies or site data.",
    category: "Browser",
    scope: "tool:browser",
    aliases: ["incognito", "private window", "private browsing"],
    mac: "Cmd+Shift+N",
    windows: "Ctrl+Shift+N",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("browser.find", "Find on page", {
    description: "Search for text in the focused website.",
    category: "Browser",
    scope: "tool:browser",
    aliases: ["find", "search page"],
    mac: "Cmd+F",
    windows: "Ctrl+F",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("browser.print", "Print page", {
    description: "Print the focused website or save it as a PDF.",
    category: "Browser",
    scope: "tool:browser",
    aliases: ["print", "pdf"],
    mac: "Cmd+P",
    windows: "Ctrl+P",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("browser.history", "Show history", {
    description: "Open the websites you have visited.",
    category: "Browser",
    scope: "tool:browser",
    aliases: ["history", "visited"],
    mac: "Cmd+Y",
    windows: "Ctrl+H",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("browser.downloads", "Show downloads", {
    description: "Open the files you have downloaded from websites.",
    category: "Browser",
    scope: "tool:browser",
    aliases: ["downloads"],
    mac: "Cmd+Option+L",
    windows: "Ctrl+J",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("browser.bookmark", "Bookmark this page", {
    description: "Save the focused website to a group.",
    category: "Browser",
    scope: "tool:browser",
    aliases: ["bookmark", "save website", "favorite"],
    mac: "Cmd+D",
    windows: "Ctrl+D",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("browser.developer_tools", "Developer tools", {
    description: "Inspect the focused website with Web Inspector.",
    category: "Browser",
    scope: "tool:browser",
    aliases: ["inspect", "devtools", "web inspector"],
    mac: "Cmd+Option+I",
    windows: "Ctrl+Shift+I",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("browser.clear_data", "Clear browsing data", {
    description: "Remove history, downloads, cookies or cached files.",
    category: "Browser",
    scope: "tool:browser",
    aliases: ["clear cookies", "clear cache", "delete history"],
    mac: "Cmd+Shift+Backspace",
    windows: "Ctrl+Shift+Delete",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("browser.annotation_undo", "Undo Browser annotation", {
    description: "Undo the last annotation edit in Browser.",
    category: "Browser",
    scope: "tool:browser",
    mac: "Cmd+Z",
    windows: "Ctrl+Z",
    allowInEditable: true,
    allowShadowing: true,
  }),
  command("browser.annotation_redo", "Redo Browser annotation", {
    description: "Redo the last annotation edit in Browser.",
    category: "Browser",
    scope: "tool:browser",
    mac: "Cmd+Shift+Z",
    windows: "Ctrl+Y",
    allowInEditable: true,
    allowShadowing: true,
  }),
];

export const shortcutCommandRegistry: ShortcutCommandDefinition[] = [
  ...shellCommands,
  ...workspaceCommands,
  ...tabAndToolCommands,
  ...toolCommands,
];

export const shortcutCommandsById = new Map(
  shortcutCommandRegistry.map((definition) => [definition.id, definition]),
);

export function defaultBindingsFor(
  definition: ShortcutCommandDefinition,
  platform: ShortcutPlatform,
): ShortcutBindingPair {
  return definition.defaults[platform];
}
