import type { Category, Thread } from "./types";

export const categoryBadge: Record<Category, string> = {
  general: "bg-text-muted/10 text-text-muted border-text-muted/20",
  "feature-requests": "bg-primary/10 text-primary border-primary/20",
  "bug-reports": "bg-danger/10 text-danger border-danger/20",
  "show-and-tell": "bg-success/10 text-success border-success/20",
};

export const categoryLabel: Record<Category, string> = {
  general: "General",
  "feature-requests": "Feature Request",
  "bug-reports": "Bug Report",
  "show-and-tell": "Show & Tell",
};

export const threads: Thread[] = [
  {
    id: 1,
    title: "Welcome to the Misty Community Forum",
    category: "general",
    author: "Misty Team",
    avatar: "MT",
    date: "Dec 2025",
    pinned: true,
    body: "Welcome to the Misty community! This is the place to ask questions, share feedback, report bugs, and show off what you're building with Misty. Please be respectful and follow the community guidelines.\n\nA few tips to get started:\n- Search before posting — your question may already be answered\n- Use the right category so others can find and help with your topic\n- Include steps to reproduce when reporting bugs\n\nWe're excited to have you here!",
    replies: [
      {
        author: "alex_dev",
        avatar: "AD",
        date: "Dec 2025",
        body: "Great to see a community forum! Looking forward to contributing.",
        likes: 12,
      },
      {
        author: "sarah_k",
        avatar: "SK",
        date: "Jan 2026",
        body: "Love the project so far. The unified browser is exactly what I needed.",
        likes: 8,
      },
    ],
    views: 1842,
  },
  {
    id: 2,
    title: "Request: Dropbox integration",
    category: "feature-requests",
    author: "clouduser42",
    avatar: "CU",
    date: "Jan 2026",
    body: "Would love to see Dropbox added as a supported provider. I use it alongside Google Drive for work and it would be great to manage both from Misty. Is this on the roadmap?",
    replies: [
      {
        author: "Misty Team",
        avatar: "MT",
        date: "Jan 2026",
        body: "Dropbox is on our roadmap! It's currently in the 'In Progress' phase. We're working on the Oauth flow and file listing Api integration. Stay tuned.",
        likes: 24,
      },
      {
        author: "dev_maria",
        avatar: "DM",
        date: "Feb 2026",
        body: "This would be amazing. I'd also love to see Box support alongside Dropbox.",
        likes: 6,
      },
      {
        author: "clouduser42",
        avatar: "CU",
        date: "Feb 2026",
        body: "Great to hear it's already being worked on. Thanks for the quick response!",
        likes: 3,
      },
    ],
    views: 634,
  },
  {
    id: 3,
    title: "Oauth token refresh fails after sleep/hibernate",
    category: "bug-reports",
    author: "linux_power",
    avatar: "LP",
    date: "Feb 2026",
    solved: true,
    body: "After my laptop wakes from suspend, Misty loses the connection to Google Drive and the Oauth token doesn't auto-refresh. I have to manually disconnect and reconnect the account.\n\nOs: Arch Linux (Wayland)\nMisty: v0.2.1\nSteps:\n1. Connect Google Drive account\n2. Suspend laptop for 30+ minutes\n3. Wake and try to browse Drive files\n4. Get 'Authentication failed' error",
    replies: [
      {
        author: "Misty Team",
        avatar: "MT",
        date: "Feb 2026",
        body: "Thanks for the detailed report! This was a known issue related to how we handled system clock changes after suspend. It's been fixed in v0.2.1 — the proxy now detects token expiry on each request and refreshes proactively.",
        likes: 15,
      },
      {
        author: "linux_power",
        avatar: "LP",
        date: "Feb 2026",
        body: "Confirmed fixed on v0.2.1. Thanks for the fast turnaround!",
        likes: 4,
      },
    ],
    views: 287,
  },
  {
    id: 4,
    title: "My multi-cloud backup workflow with Misty",
    category: "show-and-tell",
    author: "datahoarder",
    avatar: "DH",
    date: "Feb 2026",
    body: "I set up a workflow where I use Misty to mirror important documents across Google Drive and OneDrive. Every week I open Misty, select the folders I want to sync, and use the clipboard to copy them between providers.\n\nIt's not automated (yet), but it's way faster than opening two browser tabs and downloading/uploading manually. Would love to see a 'sync folder' feature in the future!",
    replies: [
      {
        author: "backup_pro",
        avatar: "BP",
        date: "Mar 2026",
        body: "This is basically my exact workflow too. A scheduled sync feature would be a game changer.",
        likes: 9,
      },
    ],
    views: 412,
  },
  {
    id: 5,
    title: "How does Misty handle large file transfers?",
    category: "general",
    author: "new_user_99",
    avatar: "NU",
    date: "Mar 2026",
    body: "I need to move around 50GB of video files between cloud providers. Can Misty handle that, or is it better suited for smaller files? Curious about any size limits or performance considerations.",
    replies: [
      {
        author: "Misty Team",
        avatar: "MT",
        date: "Mar 2026",
        body: "Misty uses Grpc streaming for transfers, so large files are handled in chunks rather than loaded into memory all at once. There's no hard file size limit. For 50GB of video, you should be fine — the main bottleneck will be your internet upload/download speed, not Misty itself.",
        likes: 11,
      },
      {
        author: "datahoarder",
        avatar: "DH",
        date: "Mar 2026",
        body: "I regularly move 10-20GB batches without issues. The progress indicator is pretty accurate too.",
        likes: 5,
      },
    ],
    views: 198,
  },
  {
    id: 6,
    title: "S3-compatible storage — any timeline?",
    category: "feature-requests",
    author: "infra_eng",
    avatar: "IE",
    date: "Mar 2026",
    body: "I self-host MinIO and would love to connect it to Misty alongside my Google Drive. The roadmap mentions S3-compatible storage as planned — is there a rough timeline for this?\n\nWould also be great for Backblaze B2 and Wasabi users.",
    replies: [
      {
        author: "Misty Team",
        avatar: "MT",
        date: "Mar 2026",
        body: "S3-compatible storage is something we're really excited about. It's currently planned for after the Dropbox/Box integration ships. No exact date yet, but it's a high-priority item for the second half of the year.",
        likes: 18,
      },
    ],
    views: 321,
  },
  {
    id: 7,
    title: "File preview not working for .heic images",
    category: "bug-reports",
    author: "photo_fan",
    avatar: "PF",
    date: "Mar 2026",
    body: "When I try to preview .heic files from my iCloud Drive, I just get a blank preview panel. Jpg and Png work fine. Is Heic supposed to be supported?\n\nOs: macOS 14.3\nMisty: v0.3.0",
    replies: [
      {
        author: "Misty Team",
        avatar: "MT",
        date: "Mar 2026",
        body: "Heic preview support is not yet implemented — we currently only handle common raster formats (Jpg, Png, Gif, Webp). We'll add Heic support in an upcoming release. Thanks for the report!",
        likes: 7,
      },
    ],
    views: 145,
  },
  {
    id: 8,
    title: "Built a script to auto-organize cloud files with Misty + Api",
    category: "show-and-tell",
    author: "script_kid",
    avatar: "SK",
    date: "Mar 2026",
    body: "I wrote a small Python script that uses the Misty Api to automatically sort files in my Google Drive by file type. Photos go into /Photos, documents into /Docs, etc. Runs on a cron job once a day.\n\nHappy to share the script if anyone's interested — it's about 60 lines of code.",
    replies: [
      {
        author: "alex_dev",
        avatar: "AD",
        date: "Mar 2026",
        body: "Please share! I've been looking for exactly this kind of automation.",
        likes: 14,
      },
      {
        author: "infra_eng",
        avatar: "IE",
        date: "Mar 2026",
        body: "This is awesome. Would love to see a community recipes/scripts section on the docs.",
        likes: 10,
      },
      {
        author: "script_kid",
        avatar: "SK",
        date: "Mar 2026",
        body: "Posted the gist on GitHub! Link in my profile. It uses the /files/list and /files/move endpoints.",
        likes: 8,
      },
    ],
    views: 523,
  },
];
