const permissionLabels: Record<string, string> = {
  "spaces.read": "View the active Space and its members",
  "messages.read": "Read conversations in the active Space",
  "messages.write": "Send and update messages in the active Space",
  "notes.read": "Read notes in the active Space",
  "notes.write": "Create and update notes in the active Space",
  "drawings.read": "View drawings in the active Space",
  "drawings.write": "Create and update drawings in the active Space",
  "tasks.read": "View tasks in the active Space",
  "tasks.write": "Create and update tasks in the active Space",
  "calendar.read": "View calendars in the active Space",
  "calendar.write": "Create events and manage calendars in the active Space",
  "roadmaps.read": "View roadmaps in the active Space",
  "roadmaps.write": "Create and update roadmaps in the active Space",
  "library.read": "View Library items in the active Space",
  "library.write": "Add and update Library items in the active Space",
  "activity.read": "View recent activity in the active Space",
  "activity.write": "Mark or clear activity in the active Space",
  "agents.read": "View agents in the active Space",
  "agents.write": "Create and manage agents in the active Space",
  "files.read": "Read files and folders you choose",
  "files.open": "Open chosen files in their native applications",
  "files.write": "Create, change, rename, and delete files and folders you choose",
  "profile.read": "View your Misty profile",
  "connections.read": "View connected accounts used by this app",
  "connections.write": "Connect or disconnect accounts used by this app",
  "mail.read": "Read mail from accounts you connect",
  "mail.write": "Draft, send, and organize mail from accounts you connect",
  "ai.read": "View Misty conversations used by this app",
  "ai.write": "Ask Misty to create or update content in this app",
  "mcp.read": "View connected MCP tools",
  "mcp.write": "Connect and manage MCP tools",
  "automations.read": "View your automations",
  "automations.write": "Create and manage automations",
  "devices.read": "View devices linked to your account",
  "devices.write": "Manage linked devices",
  "media-search.read": "Search media available to Misty",
  "media-search.write": "Add media results to files you choose",
  "search.read": "Search your Misty content",
  "browser.navigate": "Open web addresses you enter",
  "code.execute": "Run language servers on this computer",
  "code.read": "Read files in projects you choose",
  "code.write": "Change files in projects you choose",
  "terminal.execute": "Run commands on this computer",
  "clipboard.read": "Read text from your clipboard with your permission",
  "clipboard.write": "Copy text to your clipboard with your permission",
  "links.open": "Open links in your default browser",
  "ai.use": "Share this app’s visible context with Misty when you use AI",
  "transfers.read": "View file transfer status",
  "transfers.write": "Retry or dismiss file transfers",
};

export function appPermissionLabel(scope: string): string {
  return permissionLabels[scope] ?? scope;
}
