export type IntegrationCapability =
  | "chat"
  | "notes"
  | "calendar"
  | "calendar_read"
  | "calendar_write"
  | "source_control"
  | "shell"
  | "files"
  | "drawings"
  | "drawings_read"
  | "drawings_projects"
  | "drawings_comments"
  | "drawings_webhooks"
  | "social_read"
  | "social_send"
  | "social_automation"
  | "agent_tools";
