export const routes = {
  root: "/",
  account: "/account",
  accountRegister: "/account/register",
  accountSettings: "/account/settings",
  accountSignIn: "/account/signin",
  activity: "/activity",
  agents: "/agents",
  assistant: "/assistant",
  automations: "/automations",
  changelog: "/changelog",
  diagnostics: "/diagnostics",
  dock: "/dock",
  extensions: "/extensions",
  files: "/files",
  home: "/home",
  library: "/library",
  spaces: "/spaces",
  spacePersonal: "/spaces/personal",
  studio: "/studio",
  studioAgents: "/studio/agents",
  studioWorkflows: "/studio/workflows",
  providers: "/providers",
  register: "/register",
  settings: "/settings",
  signIn: "/signin",
  transfers: "/transfers",
} as const;
