export const routes = {
  root: "/",
  account: "/account",
  accountRegister: "/account/register",
  accountSettings: "/account/settings",
  accountSignIn: "/account/signin",
  activity: "/activity",
  agents: "/agents",
  // Legacy path, kept so saved bookmarks and misty:// deep links still resolve.
  // LegacyAgentRedirect forwards it to `agents`.
  assistant: "/assistant",
  automations: "/automations",
  changelog: "/changelog",
  diagnostics: "/diagnostics",
  dock: "/dock",
  extensions: "/extensions",
  files: "/files",
  invite: "/invite",
  library: "/library",
  spaces: "/spaces",
  studio: "/studio",
  studioAgents: "/studio/agents",
  studioWorkflows: "/studio/workflows",
  providers: "/providers",
  register: "/register",
  settings: "/settings",
  signIn: "/signin",
  transfers: "/transfers",
} as const;
