#!/usr/bin/env bash

set -e

NAME=rclone-serve-sftp-ssh
IP=127.0.0.1
PORT=28623
PRIVATE_KEY=/tmp/${NAME}.key
PUBLIC_KEY=/tmp/${NAME}.pub

start() {

cat >${PRIVATE_KEY} <<'#EOF'
REDACTED_LEGACY_CREDENTIAL
#EOF
chmod 600 ${PRIVATE_KEY}

cat >${PUBLIC_KEY} <<'#EOF'
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/t7p34BvEQu9GTuxmKmR626qATj+9Vt//o8y453U5I/I46wA6zjW29zhKThL7/pF4dbiXUMrLkgfSyY6wDWTnyQoWQ3U0KEdTnPQKK0CJnB2XvOq/E0mqUyZiIZO5uFB0ycOurQACeHKv1MWtxmZg9yn20dym31VBZ4thH/Xq1PndaemBO4xaWDIznxukKH9wM7uA6NLJceE8/GtTWp2vmD/lP0cWBB+LYJfy+TikNj5DDUuenUwykpPiL3FYYxTygMkbfTxGvNSL23PVFN4+1uzjFc7Lxxc5loA4MNCiTiJa8kSkaAlguOE24fNmJQNx9zVKRe8426LuPlEL+uxA5gHlJ3sBOUXgfKYDFkneI+755gFmLuXAg966D7jZaVWif4Pl05iauBw+kBm/vrsu2G/rYUya9zVIccY9ktLd1Z9tl5drK9737AiQoUS4M3vrNgBq+NJGb18EqfLon6egmClsMxU2dN80Dbx+w1uwJLo6wGMtuIWMwfGG5gAIxpU= user@rclone-serve-test
#EOF
chmod 600 ${PUBLIC_KEY}

    run rclone serve sftp --authorized-keys "${PUBLIC_KEY}" --addr ${IP}:${PORT} ${DATADIR}
    
    echo type=sftp
    echo ssh=ssh -i ${PRIVATE_KEY} -o StrictHostKeyChecking=no -p ${PORT} user@${IP}
    echo _connect=${IP}:${PORT}
}

. $(dirname "$0")/rclone-serve.bash
