export type AppTab =
  | "home"
  | "browser"
  | "terminal"
  | "code"
  | "files"
  | "spaces"
  | "assistant"
  | "agents"
  | "extensions"
  | "transfers"
  | "providers"
  | "activity"
  | "settings"
  | "account"
  | "diagnostics";
